services:
  authbridge:
    build:
      context: .
    ports:
      - 7035:7035
    volumes:
      - ./data:/data
    environment:
      - APP_NAME=AuthBridge
    hostname: authbridge
    stop_signal: SIGINT
